version: '3.9'

services:
  mysqldb:
    image: mysql:latest
    container_name: dbMySql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_LOCAL_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - orderSystem

  api:
    depends_on:
      - mysqldb
    container_name: nestjs
    image: nestjs-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - TOKEN_MERCADO_PAGO=$TOKEN_MERCADO_PAGO
      - USERID=$USERID
      - POSID=$POSID
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - orderSystem

volumes:
  db:
networks:
  orderSystem:
    driver: bridge
