FROM node:20 as builder

WORKDIR /app

COPY backend/package.json ./
COPY backend/yarn.lock ./
COPY backend/tsconfig.json ./
COPY ./backend/prisma ./backend/prisma

COPY . .

# Install app dependencies
RUN yarn
RUN yarn build

EXPOSE 3000

CMD [ "yarn", "start:migrate:prod" ]

# FROM node:20-buster
# # RUN apt-get update && \
# #   apt-get install -y openssl

# # Create app directory
# WORKDIR /app

# COPY package.json ./
# COPY yarn.lock ./
# COPY tsconfig.json ./
# COPY ./prisma ./prisma

# # Install app dependencies
# RUN yarn
# RUN yarn build

# COPY . .

# CMD [ "yarn", "start:migrate:prod" ]