FROM node:20 as builder

WORKDIR /app

COPY ./backend/package.json ./
COPY ./backend/yarn.lock ./
COPY ./backend/tsconfig.json ./
COPY ./backend/prisma ./prisma

COPY . .

RUN yarn
RUN yarn build

FROM node:20 as runner

ENV DATABASE_URL="uri"
ENV TOKEN_MERCADO_PAGO="uri"
ENV USERID="uri"
ENV POSID="uri"
ENV NODE_LOCAL_PORT="uri"

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules/
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/yarn.lock ./
COPY --from=builder /app/dist ./dist/
COPY --from=builder /app/tsconfig.json ./
COPY --from=builder /app/prisma ./prisma/

EXPOSE 3000

CMD [ "yarn", "start:migrate:prod" ]
