# GET
# Busca Produtos
###

GET http://localhost:3000/products/1
Content-Type: application/json

# POST
# Criar Produtos
###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "batata frita grande",
  "priceUnit": 8,
  "categoryID": 3
}