# GET
# Busca pedido
###

GET http://localhost:3000/orders/2
Content-Type: application/json

# POST
# Criar pedido
###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "customerID": 1,
  "amount": 44.5,
  "orderItens": [
    {
      "name": "coca-cola",
      "quantity": 1,
      "priceUnit": 5.5,
      "productID": 1
    },
    {
      "name": "X-bacon",
      "quantity": 1,
      "priceUnit": 25,
      "productID": 2
    },
    {
      "name": "batata frita media",
      "quantity": 1,
      "priceUnit": 5,
      "productID": 5
    },
    {
      "name": "sorvete casquinha",
      "quantity": 1,
      "priceUnit": 9,
      "productID": 3
    }
  ]
}