name: "01-EKS"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Plan:
    uses: viictorivo/OrderingSystem/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev

  Apply:
    needs: Plan
    uses: viictorivo/OrderingSystem/.github/workflows/aws_tf_apply.yml@main
    with:
      gh_environment: dev
    env:
      cli_config_credentials_token: "${{ secrets.TF_API_TOKEN }}"